# Generated by Django 4.0 on 2024-04-20 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postmodel',
            name='post_image',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
