# Generated by Django 4.0 on 2024-05-05 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_alter_postmodel_post_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sharecommentmodel',
            name='share_comment_image',
        ),
    ]
