# Generated by Django 4.0 on 2024-04-14 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_remove_postmodel_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='postmodel',
            name='is_shared',
            field=models.BooleanField(default=False),
        ),
    ]
