# Generated by Django 4.0 on 2024-04-14 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_postmodel_is_shared'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commentmodel',
            old_name='content',
            new_name='comment',
        ),
    ]
