# Generated by Django 4.0 on 2024-04-14 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_rename_content_commentmodel_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postmodel',
            name='comments',
        ),
    ]
