# Generated by Django 4.0 on 2024-04-14 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_remove_postmodel_comments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postmodel',
            name='shares',
        ),
        migrations.AddField(
            model_name='sharemodel',
            name='share_content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
