# Generated by Django 4.0 on 2024-04-14 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_likemodel_share_sharelikemodel_sharecommentmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='likemodel',
            name='share',
        ),
    ]
