# Generated by Django 4.0 on 2024-04-14 17:25

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_remove_likemodel_share'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentmodel',
            name='comment_image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='comment_image'),
        ),
        migrations.AlterField(
            model_name='postmodel',
            name='post_image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='post_image'),
        ),
        migrations.AlterField(
            model_name='sharecommentmodel',
            name='share_comment_image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='share_comment_image'),
        ),
    ]
