# Generated by Django 4.0 on 2024-04-14 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='role',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
