# Generated by Django 4.0 on 2024-04-16 11:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_usermodel_profile_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='Friends',
            fields=[
                ('usermodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='users.usermodel')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('friend', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friend_friendships', to='users.usermodel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_friendships', to='users.usermodel')),
            ],
            options={
                'unique_together': {('user', 'friend')},
            },
            bases=('users.usermodel',),
        ),
    ]
