# Generated by Django 4.0 on 2024-04-17 11:59

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_friends'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='cover_photo',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='cover'),
        ),
    ]
