# Generated by Django 4.0 on 2024-05-05 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_friendrequests'),
    ]

    operations = [
        migrations.AddField(
            model_name='friendrequests',
            name='is_accepted',
            field=models.BooleanField(default=False),
        ),
    ]
